# Generated by Django 4.2.1 on 2023-05-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_ticket_title_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Télécharger le fichier'),
        ),
    ]
