# Generated by Django 4.2.1 on 2023-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='image/no-image.jpg', null=True, upload_to='image/'),
        ),
    ]
