# Generated by Django 4.2.1 on 2023-06-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_ticket_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reviewed',
        ),
    ]
